# **Student Performance Analysis**

## Importing Required Libraries

### In this section, we import the Python libraries required for data manipulation and analysis. Pandas is used for data handling and NumPy is used for numerical operations.

In [1]:
# Import libraries for data manipulation
import pandas as pd
import numpy as np

## Loading the Dataset

### The student dataset is loaded into a Pandas DataFrame to perform data analysis and manipulation.

In [2]:
# Load Data 
df = pd.read_excel("Student_data.xlsx")
df.head()

,Student_ID,Name,Gender,Age,City,Program,Attendance,Total Marks,Obtained Marks,GPA,Result,Grade,Admission_Year,Semester,Year
0,UNI0001,Anaya Raza,Female,25.0,Islamabad,BSCS,91.0,550,499.0,4.0,Pass,A+,2023.0,7,4
1,UNI0002,Umar Siddiqui,Male,21.0,Islamabad,NaN,47.0,550,261.0,2.0,Pass,E,2026.0,2,1
2,UNI0003,Ayesha Qureshi,Female,24.0,Lahore,BSIT,46.0,550,252.0,1.0,Pass,E,2023.0,8,4
3,UNI0004,Hira Raza,Female,25.0,Islamabad,BSCS,73.0,550,402.0,NaN,Pass,B,2023.0,7,4
4,UNI0005,Abdullah Farooq,Male,21.0,Quetta,BSIT,44.0,550,244.0,1.0,Fail,F,2026.0,2,1

## Dataset Overview

### This section provides information about the structure of the dataset, including the number of rows, columns, and data types.

In [3]:
# Number of rows and columns
print("Shape:", df.shape)

Shape: (200, 15)

In [4]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      200 non-null    str
 1   Name            200 non-null    str
 2   Gender          200 non-null    str
 3   Age             199 non-null    float64
 4   City            198 non-null    str
 5   Program         197 non-null    str
 6   Attendance      199 non-null    float64
 7   Total Marks     200 non-null    int64
 8   Obtained Marks  199 non-null    float64
 9   GPA             198 non-null    float64
 10  Result          200 non-null    str
 11  Grade           200 non-null    str
 12  Admission_Year  199 non-null    float64
 13  Semester        200 non-null    int64
 14  Year            200 non-null    int64
dtypes: float64(5), int64(3), str(7)
memory usage: 31.9 KB

## Descriptive Statistics
### This provides a statistical summary of numerical columns including mean, standard deviation, minimum, maximum, and quartile values.
### It helps in understanding the overall distribution and spread of the data.

In [5]:
df.describe()

,Age,Attendance,Total Marks,Obtained Marks,GPA,Admission_Year,Semester,Year
count,199.000000,199.000000,200.0,199.000000,198.000000,199.000000,200.000000,200.000000
mean,22.984925,71.271357,550.0,393.427136,2.823232,2024.517588,4.475000,2.485000
std,1.182692,17.898048,0.0,94.975826,0.867674,1.081732,2.248254,1.079631
min,21.000000,0.000000,550.0,190.000000,1.000000,2023.000000,1.000000,1.000000
25%,22.000000,55.000000,550.0,302.500000,2.000000,2024.000000,3.000000,2.000000
50%,23.000000,72.000000,550.0,395.000000,3.000000,2025.000000,4.500000,2.500000
75%,24.000000,87.000000,550.0,478.000000,3.500000,2025.000000,6.000000,3.000000
max,25.000000,100.000000,550.0,550.000000,4.000000,2026.000000,8.000000,4.000000

## Total Students
### This shows the total number of students in the dataset, defining the overall size of the analysis.

In [6]:
print("Total Students:", len(df))

Total Students: 200

## Gender Distribution
### Students are distributed across male and female categories, showing the demographic balance of the dataset.

In [7]:
print(df["Gender"].value_counts())

Gender
Female    103
Male       97
Name: count, dtype: int64

## Program-wise Student Count

### This analysis helps identify which academic program has the highest enrollment.

In [8]:
print(df["Program"].value_counts())

Program
BSSE               32
BSCS               30
BSIT               28
BS Data Science    25
BSAI               25
BBA                24
BCom               17
BS Mathematics     16
Name: count, dtype: int64

## City-wise Student Distribution

### This analysis identifies the number of students belonging to each city. It helps understand the geographical distribution of students in the dataset.

In [9]:
print(df["City"].value_counts())

City
Lahore        30
Peshawar      29
Faisalabad    29
Multan        26
Islamabad     22
Quetta        22
Rawalpindi    20
Karachi       19
Hyerabad       1
Name: count, dtype: int64

## Top Performing Students

### This section identifies the highest-performing students based on obtained marks.

In [10]:
top_students = df.nlargest(
    10,
    "Obtained Marks"
)

top_students[
    ["Name",
     "Program",
     "Obtained Marks"]
]

                Name          Program  Obtained Marks
39      Hussain Khan   BS Mathematics           550.0
125      Anaya Malik              BBA           550.0
132     Fatima Malik             BSAI           549.0
162        Iqra Butt             BSSE           549.0
23        Laiba Khan             BSCS           548.0
41   Fatima Chaudhry             BSIT           547.0
20     Laiba Qureshi             BSIT           546.0
128       Ahsan Butt   BS Mathematics           545.0
183       Usman Raza             BSAI           545.0
178      Ahmed Malik  BS Data Science           541.0

## Students Requiring Academic Attention

### This analysis identifies students with the lowest marks who may require academic support.

In [11]:
low_students = df.nsmallest(
    10,
    "Obtained Marks"
)

low_students[
    ["Name",
     "Program",
     "Obtained Marks"]
]

                Name          Program  Obtained Marks
192     Zainab Malik             BSCS           190.0
69       Usman Ahmed              BBA           200.0
100    Ahsan Qureshi   BS Mathematics           230.0
4    Abdullah Farooq             BSIT           244.0
199    Laiba Qureshi             BSAI           245.0
109       Usman Shah              BBA           249.0
53     Noor Siddiqui             BSCS           251.0
2     Ayesha Qureshi             BSIT           252.0
120        Noor Butt   BS Mathematics           253.0
163       Anaya Butt  BS Data Science           253.0

## Pass and Fail Analysis

### Students are classified as Pass or Fail based on their obtained marks.

In [12]:
df["Result"] = np.where(
    df["Obtained Marks"] >= 250,
    "Pass",
    "Fail"
)

df["Result"].value_counts()

Result
Pass    193
Fail      7
Name: count, dtype: int64

## Program-wise Pass Rate

### This analysis evaluates the success rate of students across different programs.

In [13]:
pd.crosstab(
    df["Program"],
    df["Result"]
)

Result           Fail  Pass
Program
BBA                 2    22
BCom                0    17
BS Data Science     0    25
BS Mathematics      1    15
BSAI                1    24
BSCS                1    29
BSIT                1    27
BSSE                1    31

## Program-wise Median GPA 
### Median GPA represents the typical performance of students in each program with minimal impact from outliers.

In [14]:
program_gpa = df.groupby("Program")["GPA"].median()
print(program_gpa)

Program
BBA                2.5
BCom               2.5
BS Data Science    3.0
BS Mathematics     2.5
BSAI               3.0
BSCS               3.0
BSIT               3.0
BSSE               3.0
Name: GPA, dtype: float64

## Program-wise Mean GPA
### Mean GPA helps compare the overall academic performance across different programs.

In [15]:
print(df.groupby("Program")["GPA"].mean())

Program
BBA                2.750000
BCom               2.647059
BS Data Science    2.880000
BS Mathematics     2.687500
BSAI               3.000000
BSCS               2.913793
BSIT               2.833333
BSSE               2.843750
Name: GPA, dtype: float64

## Missing Values Analysis

### Missing values can affect the quality of analysis. We identify missing values in each column before proceeding further and remove them.

In [16]:
print(df.isnull().sum())

Student_ID        0
Name              0
Gender            0
Age               1
City              2
Program           3
Attendance        1
Total Marks       0
Obtained Marks    1
GPA               2
Result            0
Grade             0
Admission_Year    1
Semester          0
Year              0
dtype: int64

In [17]:
df = df.dropna()   
print(df.isnull().sum())

Student_ID        0
Name              0
Gender            0
Age               0
City              0
Program           0
Attendance        0
Total Marks       0
Obtained Marks    0
GPA               0
Result            0
Grade             0
Admission_Year    0
Semester          0
Year              0
dtype: int64

## Duplicate Records Analysis

### Duplicate records can create bias in analysis. Therefore, we identify and remove duplicate entries.

In [18]:
# Total duplicates
df.duplicated("Program").sum()

np.int64(182)

In [19]:
# Remove duplicates
df = df.drop_duplicates("Program")
df.duplicated("Program").sum()

np.int64(0)